"""initial migration

Revision ID: bb4b29155e0f
Revises: 
Create Date: 2018-12-27 16:59:10.492295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4b29155e0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable='')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
